### ISSUE TITLE
@cjkcr 我绑定好域名后，也遇到了你这个错误。别管它，直接用新域名替代自己的ChatGPT应用中的 api.openai.com，我的应用就能正常运行了。

### ISSUE THREAD

**Issue by mattcshan** [noobnooc/noobnooc#10]
@cjkcr 我绑定好域名后，也遇到了你这个错误。别管它，直接用新域名替代自己的ChatGPT应用中的 api.openai.com，我的应用就能正常运行了。
请问是用这样的域名吗?  https://www.example.com/v1/chat/completions, 另外chatgpt的API key在哪里输入, 不好意思打扰, 实在不懂程序.
_Originally posted by @jayleecn in https://github.com/noobnooc/noobnooc/discussions/9#discussioncomment-5204970_

**Comment by jayleecn** [comment]
>         @cjkcr 我绑定好域名后，也遇到了你这个错误。别管它，直接用新域名替代自己的ChatGPT应用中的 api.openai.com，我的应用就能正常运行了。
> 
> 请问是用这样的域名吗?  https://www.example.com/v1/chat/completions, 另外chatgpt的API key在哪里输入, 不好意思打扰, 实在不懂程序.
> 
> _Originally posted by @jayleecn in https://github.com/noobnooc/noobnooc/discussions/9#discussioncomment-5204970_
> 
>       

这个程序，只是给你搭建一个替代api.openai.com 的代理服务器，你的api key 是在你的应用程序（比如 chatgpt chrome插件）里输入的，跟这个代理服务器没关系的

需要你把应用程序（比如 chatgpt chrome插件）的代理服务器，设置成你的域名，或者改代码，把api.openai.com改成你的域名 www.example.com

**Comment by noobnooc** [comment]
这个只是代理 OpenAI API 地址的，和 Key 这些都没有关系，还要看你的使用场景支不支持替换 地址

**Comment by mattcshan** [comment]
感谢回复.
